name: patchtst
type: transformer
d_model: 128
d_ff: 256
e_layers: 3
n_heads: 16
patch_len: 16
stride: 8
dropout: 0.2
fc_dropout: 0.2
head_dropout: 0.0
activation: gelu
revin: 1
affine: 0
subtract_last: 0
decomposition: 0
kernel_size: 25
individual: 0
