name: timemixer
type: mlp
d_model: 16
d_ff: 32
e_layers: 2
down_sampling_layers: 3
down_sampling_window: 2
down_sampling_method: avg
decomp_method: moving_avg
moving_avg: 25
top_k: 5
channel_independence: 1
use_norm: 1
dropout: 0.1
